export const indiaStatesWithDistricts: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "YSR Kadapa",
  ],

  "Arunachal Pradesh": [
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "Lower Subansiri",
    "Upper Subansiri",
    "West Siang",
    "East Siang",
  ],

  "Assam": [
    "Baksa",
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Darrang",
    "Dhemaji",
    "Dibrugarh",
    "Goalpara",
    "Guwahati",
    "Jorhat",
    "Kamrup",
    "Karimganj",
    "Nagaon",
    "Tinsukia",
  ],

  "Bihar": [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Begusarai",
    "Katihar",
  ],

  "Chhattisgarh": [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Korba",
    "Raigarh",
    "Rajnandgaon",
  ],

  "Delhi": [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "South Delhi",
    "South East Delhi",
    "West Delhi",
  ],

  "Gujarat": [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
  ],

  "Haryana": [
    "Ambala",
    "Faridabad",
    "Gurugram",
    "Hisar",
    "Karnal",
    "Panipat",
    "Rohtak",
  ],

  "Karnataka": [
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Mysuru",
    "Mandya",
    "Tumakuru",
    "Udupi",
    "Dharwad",
    "Belagavi",
  ],

  "Kerala": [
    "Thiruvananthapuram",
    "Kollam",
    "Pathanamthitta",
    "Alappuzha",
    "Kottayam",
    "Idukki",
    "Ernakulam",
    "Thrissur",
    "Palakkad",
    "Malappuram",
    "Kozhikode",
    "Wayanad",
    "Kannur",
    "Kasaragod",
  ],

  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Satna",
    "Rewa",
  ],

  "Maharashtra": [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
  ],

  "Odisha": [
    "Bhubaneswar",
    "Cuttack",
    "Puri",
    "Balasore",
    "Berhampur",
    "Rourkela",
  ],

  "Punjab": [
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
  ],

  "Rajasthan": [
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Ajmer",
    "Kota",
    "Bikaner",
  ],

  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Erode",
    "Vellore",
  ],

  "Telangana": [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahabubnagar",
  ],

  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Varanasi",
    "Prayagraj",
    "Noida",
    "Ghaziabad",
    "Agra",
    "Meerut",
  ],

  "Uttarakhand": [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Nainital",
  ],

  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Hooghly",
    "Durgapur",
    "Asansol",
    "Siliguri",
  ],
};
